#!/usr/bin/env python
"""A CLI utility to automate repetitive tasks in Mage development."""

__author__ = "jhckragh@gmail.com (Jacob Kragh)"
__version__ = "0.1.4"

import sys
from optparse import OptionParser
from magetool.libraries.util import get_prog

def main():
    usage = """Usage: magetool [OPTION]... ACTION COMMAND ARG

The following commands are supported:
    block
    controller
    helper
    layout
    model
    module

See 'magetool help COMMAND' for more information on a specific command."""
    version = "%prog version " + __version__
    parser = OptionParser(usage=usage, version=version, add_help_option=False)
    parser.add_option("-f", "--frontname", dest="front_name")
    parser.add_option("-h", "--help", action="store_true", dest="show_help")
    parser.add_option("-o", "--override", action="store_true", dest="override")
    parser.add_option("-s", "--superclass", dest="superclass")
    parser.add_option("-r", "--router", dest="router")
    parser.add_option("-t", "--table", dest="table")

    options, args = parser.parse_args()
    if options.show_help:
        print usage
        return
    if not len(args) > 1:
        parser.error("incorrect number of arguments")
    kwargs = dict([(k, v) for k, v in options.__dict__.items()
                  if not k.startswith("__") and v != None])

    method, module = [arg.lower() for arg in args[:2]]
    cls = module.capitalize()
    module_import = "from magetool.commands.%s import %s as cls" % (module, cls)
    try:
        exec module_import
    except ImportError:
        msg = "%s: error: command '%s' not implemented\n" % (get_prog(), module)
        sys.stderr.write(msg)
        sys.exit(2)

    if method == "help":
        getattr(cls, "help")()
        return

    obj = cls(**kwargs)
    try:
        getattr(obj, method)(*args[2:])
    except AttributeError:
        msg = "%s: error: action '%s' not implemented\n" % (get_prog(), method)
        sys.stderr.write(msg)
        sys.exit(2)

if __name__ == "__main__":
    main()
